-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 20:11:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_ti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_ti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ti` DEFAULT CHARACTER SET utf8 ;
USE `bd_ti` ;

-- -----------------------------------------------------
-- Table `bd_ti`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ti`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `processador` VARCHAR(45) NULL,
  `placamae` VARCHAR(45) NULL,
  `fonte` VARCHAR(45) NULL,
  `ram` VARCHAR(45) NULL,
  `video` VARCHAR(45) NULL,
  `acessorios` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `dataentrada` DATE NULL,
  `orcamento` VARCHAR(45) NULL,
  `observacao` VARCHAR(500) NULL,
  `queixa` VARCHAR(500) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
